# Site settings
title: mbech/blog 
email: matt@mbech.net
description: > # this means to ignore newlines until "baseurl:"
  My very own generic blog for documenting things I am working on and
  learning about.  (Web development, programming,
  and getting the hang of Jekyll.)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: mbech 

# Build settings
markdown: kramdown
